apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: bookstore
  annotations:
    test: test1
spec:
  replicas: 1
  minReadySeconds: 9
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
