apiVersion: v1
kind: Namespace
metadata:
  name: bookstore1
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
  namespace: bookstore1
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-3
---
