apiVersion: v1
kind: Namespace
metadata:
  name: bookstore2
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
  namespace: bookstore2
  annotations:
    configsync.gke.io/cluster-name-selector: cluster-10
---
